apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        app: mariadb
spec:
    ports:
    - name: mysql
        port: 3306
    clusterIP: None
    selector:
        app: mysql
