services:
  manager:
    build: ./manager/
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"
      - "./manager/playbooks:/playbooks"
  dev:
    build: ./base/
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - dev-containers:/var/lib/containers
  testing:
    build: ./base/
    privileged: true
    cap_add:
      - ALL
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - testing-containers:/var/lib/containers
volumes:
  dev-containers:
  testing-containers:
