= Exercise 6

In this exercise we will be exploring Docker Compose _and_ Ansible, a strange
but not unheard of combination. Here is the scenario:

====
You work for InnoTech, a company that designs custom web apps. InnoTech has
three employees: You (ops), Robert De Niro (the boss), Charlie Murphy (dev),
and Curtis Mayfield (QA). They need two environments set up where they have
_complete_ control: dev and testing. They want to run a container runtime
called https://podman.io/[podman].

Fortunately, due to a nagging professor you had, you designed a system that
automates as much of this process as possible. You have docker running on a
server (we're going to use our own machine for this part) and a
`docker-compose.yml` file that sets up three services: manager, dev, and
testing. Once you bring everything up, you can start a bash shell on
manager and use Ansible to handle the heavy lifting of setting up
environments.

Unfortunately, last night you drank some bad pickle juice and it has caused
you to lose your short-term memory. You can't remember what you did, or how
you did it. The code looks brand-new to you, and it's like you've never used
Docker Compose or Ansible before.
====

== Goal

Update the https://github.com/rxt1077/it610[class repo] and take a look at
"your" code in the `exercises/6` directory. See if you can:

. Figure out what it is doing
. Bring everything up with `docker-compose up`
. Start a bash shell on the manager service
. Run the playbooks in the /playbooks directory

== Submission

Send me a screen shot of the output after the playbooks have run.
