= Kubernetes

== Local Options

[.shrink]
* https://kubernetes.io/docs/tasks/tools/install-minikube/[minikube] - Single-machine solution for developing on / testing Kubernetes.
* https://www.docker.com/products/docker-desktop[Docker Desktop] - Supports running a single-machine Kubernetes instance. Edit settings from the task-bar icon.
* https://k3s.io/[k3s] - Lightweight Kubernetes that can run on embedded devices. Want k8s on an RPI? This is it.
* https://kubernetes.io/docs/setup/learning-environment/kind/[Kind] - Runs Kubernetes inside a Docker container
* https://www.katacoda.com/courses/kubernetes/playground[Katacoda Simulations] - Run a temporary environment in a web page

== Kubectl

* The most common CLI to a Kubernetes cluster
* Can switch between contexts (different clusters)
* Can apply objects, read logs, get status, etc.
* Most things build off of these commands or at least reference them.

=== Kubectl Example

[source, console]
----
C:\Users\rxt1077\it610\docs\slides>kubectl cluster-info
Kubernetes master is running at https://kubernetes.docker.internal:6443
KubeDNS is running at https://kubernetes.docker.internal:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

C:\Users\rxt1077\it610\docs\slides>kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority: C:\Users\rxt1077\.minikube\ca.crt
    server: https://192.168.18.66:8443
  name: minikube
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: minikube
  user:
    client-certificate: C:\Users\rxt1077\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\rxt1077\.minikube\profiles\minikube\client.key
----

== Pods

* A pod is the minimum unit of compute in Kubernetes. It typically runs a single
  container.
* `kubectl get pod` is a good starting point when troubleshooting
* `kubectl describe <pod-name>` will give you even more info

=== Pod Example

[source, console]
----
C:\Users\rxt1077\it610\docs\slides>kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4
deployment.apps/hello-node created

C:\Users\rxt1077\it610\docs\slides>kubectl get pod
NAME                          READY   STATUS    RESTARTS   AGE
hello-node-7dc7987866-xnbxz   1/1     Running   0          22s

C:\Users\rxt1077\it610\docs\slides>kubectl describe pod hello-node-7dc7987866-xnbxz
Name:         hello-node-7dc7987866-xnbxz
Namespace:    default
Priority:     0
Node:         docker-desktop/192.168.65.3
Start Time:   Thu, 09 Jul 2020 16:22:31 -0400
Labels:       app=hello-node
              pod-template-hash=7dc7987866
Annotations:  <none>
Status:       Running
IP:           10.1.0.7
IPs:
  IP:           10.1.0.7
Controlled By:  ReplicaSet/hello-node-7dc7987866
Containers:
  echoserver:
    Container ID:   docker://e908a98fa417af250b33ab1e38427891ab61d3f13dd5bacdc4ef418c488c8aa2
    Image:          k8s.gcr.io/echoserver:1.4
    Image ID:       docker-pullable://k8s.gcr.io/echoserver@sha256:5d99aa1120524c801bc8c1a7077e8f5ec122ba16b6dda1a5d3826057f67b9bcb
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 09 Jul 2020 16:22:49 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2vnsb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-2vnsb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2vnsb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                     Message
  ----    ------     ----  ----                     -------
  Normal  Scheduled  73s   default-scheduler        Successfully assigned default/hello-node-7dc7987866-xnbxz to docker-desktop
  Normal  Pulling    72s   kubelet, docker-desktop  Pulling image "k8s.gcr.io/echoserver:1.4"
  Normal  Pulled     55s   kubelet, docker-desktop  Successfully pulled image "k8s.gcr.io/echoserver:1.4"
  Normal  Created    55s   kubelet, docker-desktop  Created container echoserver
  Normal  Started    55s   kubelet, docker-desktop  Started container echoserver
----

== ReplicaSets

* A ReplicaSet is a grouping of pods that Kubernetes attempts to keep running
* Kubernetes can detect failure (configurable) and restart a pod
* Kubernetes will back-off if something keeps failing

=== ReplicaSet Example

[source, console]
----
C:\Users\rxt1077\it610\docs\slides>kubectl get replicasets
NAME                    DESIRED   CURRENT   READY   AGE
hello-node-7dc7987866   1         1         1       4m4s

C:\Users\rxt1077\it610\docs\slides>kubectl describe replicaset hello-node-7dc7987866
Name:           hello-node-7dc7987866
Namespace:      default
Selector:       app=hello-node,pod-template-hash=7dc7987866
Labels:         app=hello-node
                pod-template-hash=7dc7987866
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/hello-node
Replicas:       1 current / 1 desired
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=hello-node
           pod-template-hash=7dc7987866
  Containers:
   echoserver:
    Image:        k8s.gcr.io/echoserver:1.4
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age    From                   Message
  ----    ------            ----   ----                   -------
  Normal  SuccessfulCreate  5m29s  replicaset-controller  Created pod: hello-node-7dc7987866-xnbxz
----

== Deployments

* A Deployment creates ReplicaSets to support the _deployment_ of an app
* Deployments also support update strategies

=== Deployment Example

[source, console]
----
C:\Users\rxt1077\it610\docs\slides>kubectl get deployments
NAME         READY   UP-TO-DATE   AVAILABLE   AGE
hello-node   1/1     1            1           7m18s

C:\Users\rxt1077\it610\docs\slides>kubectl describe deployment hello-node
Name:                   hello-node
Namespace:              default
CreationTimestamp:      Thu, 09 Jul 2020 16:22:31 -0400
Labels:                 app=hello-node
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=hello-node
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=hello-node
  Containers:
   echoserver:
    Image:        k8s.gcr.io/echoserver:1.4
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   hello-node-7dc7987866 (1/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  7m28s  deployment-controller  Scaled up replica set hello-node-7dc7987866 to 1
----

== Working with YAML objects

* You'll probably want to define your objects in yaml files instead of just via
  the command line.
* `kubectl apply -f <file>` will apply your file to make the cluster provide the
  resources you specified.
* Similar to ansible, this is _descriptive_: if you want three replicas and you
  already have two, it'll just make the third.

=== YAML Deployment Example

[source, yml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80
----

=== YAML from a running object

[source, yml]
----
C:\Users\rxt1077\it610\docs\slides>kubectl get deployment -o yaml
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2020-07-09T20:22:31Z"
    generation: 1
    labels:
      app: hello-node
    name: hello-node
    namespace: default
    resourceVersion: "1816"
    selfLink: /apis/apps/v1/namespaces/default/deployments/hello-node
    uid: 31356fed-0365-49df-8327-3c3c6ff0cb32
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hello-node
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hello-node
      spec:
        containers:
        - image: k8s.gcr.io/echoserver:1.4
          imagePullPolicy: IfNotPresent
          name: echoserver
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-07-09T20:22:49Z"
      lastUpdateTime: "2020-07-09T20:22:49Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-07-09T20:22:31Z"
      lastUpdateTime: "2020-07-09T20:22:49Z"
      message: ReplicaSet "hello-node-7dc7987866" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
----

== Services

Services make ports on pods available to other parts of the cluster _or_ the
outside world:

[source, console]
----
C:\Users\rxt1077\it610\docs\slides>kubectl expose deployment hello-node --type=LoadBalancer --port=8080
service/hello-node exposed

C:\Users\rxt1077\it610\docs\slides>kubectl get services
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
hello-node   LoadBalancer   10.105.154.187   localhost     8080:30031/TCP   100s
kubernetes   ClusterIP      10.96.0.1        <none>        443/TCP          32m
----

== Resources

* https://kubernetes.io/docs/reference/kubectl/cheatsheet/[kubectl Cheat sheet]
* https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Deployments]
* https://kubernetes.io/docs/tutorials/hello-minikube/[Hello Minikube]
* https://kubernetes.io/docs/concepts/services-networking/service/[Services]
