version: "3"
services:
  manager:
    build: ./manager/
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"
      - "./manager/playbooks:/playbooks"
  dev:
    build: ./base/
    privileged: true
    cap_add:
      - ALL
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  testing:
    build: ./base/
    privileged: true
    cap_add:
      - ALL
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
