= Exercise 8

Inside the `exercises/8` directory you will find a `db-k8s.yml` file that has
all of the objects we discussed during the presentation. Your goal for this
exercise is to `apply` those objects to your local Kubernetes instance using
kubectl and explore the running system using the `get`, `describe`, and `logs`
commands. Feel free to try some database operations as well, you can get a
bash prompt on any pod using `kubectl exec` just like you would with Docker.

== Questions

[qanda]
A systems architect was using a stock Docker Hub image with a custom ENTRYPOINT point script she had designed. This required a Dockerfile, BASH script, and a directory to store them. When she migrated to Kubernetes she was able to do this all in one YAML file. Describe how this is possible.::
    {empty}
Why are *Services* essential to replication?::
    {empty}
Why do we define two *Deployments* for our example?::
    {empty}
How can our database deployment be improved?::
    {empty}
Compare and contrast Kubernetes *PersistentVolumeClaims* with Docker compose named volumes.::
    {empty}
What does Kubernetes do when the `db-r` pod fails because `db-rw` is not up yet?::
    {empty}
