= Exercise 2

In this exercise we will be:

. Installing https://github.com/jay0lee/GAM[GAM] on an Unbuntu container via
  their installation script.
. Creating a Debian package for GAM.
. Creating a Dockerfile for a container that installs GAM from your package.

== Running the Ubuntu Container

`git pull` the https://github.com/rxt1077/it610.git[class repo] to get the most
up-to-date version. You may need to `git stash` your changes if you have made
any: https://git-scm.com/docs/git-stash.

`cd` into `exercises/2` and build the container, tagging it as `exercise-2`.
Then interactively run `bash` on the container, bind mounting `output` on the
host to `/output` on the container:

[source, console]
----
PS C:\Users\rxt1077\it610\exercises\2> docker build -t exercise-2 .
Sending build context to Docker daemon   2.56kB
Step 1/3 : FROM ubuntu:20.04
 ---> 1d622ef86b13
Step 2/3 : RUN apt-get update
 ---> Using cache
 ---> fded07b64335
Step 3/3 : RUN apt-get install -y curl python3
 ---> Using cache
 ---> c3766b487a7e
Successfully built c3766b487a7e
Successfully tagged exercise-2:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to doubl
e check and reset permissions for sensitive files and directories.
PS C:\Users\rxt1077\it610\exercises\2> docker run -it -v "output:/output" exercise-2 bash
root@9d2796906f2c:/# <1>
----
<1> Notice how the prompt changed? We are now executing commands inside our container.

== Installing GAM

Read the GAM README.md in https://github.com/jay0lee/GAM[their GitHub
repository] and follow the directions to install GAM from the BASH prompt on
the running container.

NOTE: The script will ask you if you have a full browser. You can say 'N', but
it really shouldn't matter.

WARNING: The script will ask if you want to set up a Google API project for
GAM. Say 'N' because will will not actually be linking this to a real Google
admin account.

Read the output from the installation script _carefully_. You will need to know
where you can find the `gam` binary.

== Creating a Debian Package

Follow
http://www.sj-vs.net/creating-a-simple-debian-deb-package-based-on-a-directory-structure/[this
guide] to set up the directory structure and build a package in the `/output`
directory. Remember, the `/output` directory on the container is linked to the
`output` directory on the host.

You can use your host OS file managers/text editors in the `output` directory or
if you are feeling adventurous you can `apt-get install neovim`,
`apt-get install vim`, `apt-get install nano`, or any other terminal editor
directly on the container and use them.

Make yourself the Maintainer in the metadata, take some credit for your hard
work! When you are all done, type `exit` to exit the shell. Your `.deb` file
should be in the `output` directory on the host

== Creating a Dockerfile for an Image That Uses Your Package

Take a look at the Dockerfile in the main exercise directory:
`it610/exercises/2`. Makeyour own Dockerfile in the `output` directory that
copies your `.deb` package into the image and installs it with `dpkg -i`.

Relevant documentation can be found here:

* https://docs.docker.com/engine/reference/builder/#from[Dockerfile reference: FROM]
* https://docs.docker.com/engine/reference/builder/#copy[Dockerfile reference: COPY]
* https://docs.docker.com/engine/reference/builder/#run[Dockerfile reference: RUN]
* https://linux.die.net/man/1/dpkg[dpkg man page]

== Questions

Please answer the following questions in the text submission section of the
assignment:

[qanda]
Are there any security concerns with installing an application like GAM via a shell script? Give examples.::
    {empty}
What is the GAM installation script written in? What does it do?::
    {empty}
What are the advantages of having a deb package for GAM as opposed to just using the installation script? What are the disadvantages?::
    {empty}
What was the hardest part of this exercise?::
    {empty}
