= Exercise 3

In this exercise we will be

. Creating a new volume in Docker
. Running a postgres container with the volume mounted
. Creating a new database on the volume
. Backing up the volume

== Creating a Volume

Create a volume with the `volume create` command and check to see if it is
there with the `volume ls` command.

[source, console]
----
PS C:\Users\rxt1077\it610\exercises\3> docker volume create exercise3-db
exercise3-db
PS C:\Users\rxt1077\it610\exercises\3> docker volume ls
DRIVER              VOLUME NAME
local               db-data
----

== Running PostgreSQL

Now let's run a postgres container in the background with our volume mounted in
`/var/lib/postgresql/data`, which is the path where the PostgreSQL database
information is stored by default:

[source, console]
----
PS C:\Users\rxt1077\it610\exercises\3> docker run -d --mount source=exercise3-db,target=/var/lib/postgresql/data -e POSTGRES_PASSWORD=changeme postgres <1>
Unable to find image 'postgres:latest' locally
latest: Pulling from library/postgres
8559a31e96f4: Pull complete
<snip>
Digest: sha256:9ba6355d27ba9cd0acda1e28afaae4a5b7b2301bbbdc91794dcfca95ab08d2ef
Status: Downloaded newer image for postgres:latest
99dc65697ce9c13d7ae97c042687f25fa70addcc24539371d4476d21bac50cec
PS C:\Users\rxt1077\it610\exercises\3> docker ps <2>
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
99dc65697ce9        postgres            "docker-entrypoint.s…"   27 seconds ago      Up 27 seconds       5432/tcp            boring_pike
----
<1> Here is an explanation of the options:
* `d`: run in the background
* `--mount source=exercise3-db,target=/var/lib/postgresql/data`: mount the
  `exercise3-db` local volume in the `/var/lib/postgresql/data` directory of the
  container
* `-e POSTGRES_PASSWORD=changeme`: set the environment variable fo the postgres
  password to `changeme`. PostgreSQL won't start without a password.
* `postgres`: run the postgres image
<2> This is just to confirm that it is running

You can also check the logs to see how things went with
`docker logs <CONTAINER ID>` where `<CONTAINER ID>` is the id from your `ps` command.

== Creating a New Database

The easiest way to create a new database on our running container would be with
the psql command. Fortunately the psql command is already on our container so we
can `exec` it from there. Let's connect to our database and put some data in there:

[source, console]
----
PS C:\Users\rxt1077\it610\exercises\3> docker exec -it <CONTAINER ID> psql --username=postgres <1>
psql (12.3 (Debian 12.3-1.pgdg100+1))
Type "help" for help.

postgres=# CREATE DATABASE top_secret; <2>
CREATE DATABASE
postgres=# \c top_secret
You are now connected to database "top_secret" as user "postgres".
top_secret=# CREATE TABLE spies (name VARCHAR(64));
CREATE TABLE
top_secret=# INSERT INTO spies (name) VALUES ('Bob');
INSERT 0 1
top_secret=# \q <3>
----
<1> Here is an explanation of the options:
* `exec`: run a command _on an already running container_
* `-it`: run interactively
* `<CONTAINER ID>`: your container id as listed in the `ps` output above
* `psql`: run the psql command (command line SQL client)
* `--username=postgres`: this argument is passed to the `psql` command, it says
  you want to connect as the default postgres user
<2> These psql commands create a bit of data for us to use
<3> `\q` exits psql

== Backing up the Database Directory

Now we will start another container, that uses the same volumes as our postgres
container. On the new container we will use the `tar` command to make a
compressed archive the the database directory.

[source, console]
----
PS C:\Users\rxt1077\it610\exercises\3> docker run --rm --volumes-from <CONTAINER ID> -v "$(pwd):/backup" ubuntu tar zcf /backup/db-backup.tar.gz /var/lib/postgresql/data <1>
tar: Removing leading `/' from member names
PS C:\Users\rxt1077\it610\exercises\3> ls


    Directory: C:\Users\rxt1077\it610\exercises\3


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/11/2020   4:20 PM        5740117 db-backup.tar.gz
----
<1> This is a long command, so lets take it argument-by-argument:
* `run`: start a new container and run a command on it
* `--rm`: don't archive this container when we are done, it's temporary
* `--volumes-from <CONTAINER ID>`: give us the same volumes at the same
  mountpoints as our running postgres container
* `-v "$(pwd):/backup"`: bind mount the local working directory to
  `/backup` on the container we are creating
* `ubuntu`: use the `ubuntu` base image
* `tar zcf /backup/db-backup.tar.gz /var/lib/postgresql/data`: this is the
  command that is run on the container. It creates a compressed tar archive
  from the database directory.

== Deliverables

Submit your `db-backup.tar.gz` file as your work for this exercise.

== Resources

* https://docs.docker.com/storage/volumes/[Docker Documentation: Use volumes]
* https://hub.docker.com/_/postgres[Docker Hub: postgres]

