= Exercise 3

In this exercise we will be:

. Installing https://github.com/jay0lee/GAM[GAM] on an Ubuntu container via
  their installation script.
. Creating a Debian package for GAM.
. Creating a Dockerfile for a container that installs GAM from your package.

== Running the Ubuntu Container

`git pull` the https://github.com/rxt1077/it610.git[class repo] to get the most
up-to-date version. You may need to `git stash` your changes if you have made
any: https://git-scm.com/docs/git-stash.

`cd` into `exercises/3` and build the container, tagging it as `exercise-3`.
Then interactively run `bash` on the container, bind mounting `output` on the
host to `/output` on the container:

[source, console]
----
PS C:\Users\rxt1077\it610\exercises\3> docker build -t exercise-3 .
Sending build context to Docker daemon   2.56kB
Step 1/3 : FROM ubuntu:20.04
 ---> 1d622ef86b13
Step 2/3 : RUN apt-get update
 ---> Using cache
 ---> fded07b64335
Step 3/3 : RUN apt-get install -y curl python3
 ---> Using cache
 ---> c3766b487a7e
Successfully built c3766b487a7e
Successfully tagged exercise-3:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to doubl
e check and reset permissions for sensitive files and directories.
PS C:\Users\rxt1077\it610\exercises\2> docker run -it -v "$(pwd)/output:/output" exercise-3 bash
root@9d2796906f2c:/# <1>
----
<1> Notice how the prompt changed? We are now executing commands inside our
container.

WARNING: Be sure the path for the bind mount is absolute! It will fail silently
otherwise. `$(pwd)/output:/output` should give the absolute path in Windows and
MacOS.

== Installing GAM

Read the GAM README.md in https://github.com/jay0lee/GAM[their GitHub
repository] and follow the directions to install GAM from the BASH prompt on
the running container.

NOTE: The script will ask you if you have a full browser. You can say 'N', but
it really shouldn't matter.

WARNING: The script will ask if you want to set up a Google API project for
GAM. Say 'N' because will will not actually be linking this to a real Google
admin account.

Read the output from the installation script _carefully_. You will need to know
where you can find the `gam` binary.

== Creating a Debian Package

Follow https://linuxconfig.org/easy-way-to-create-a-debian-package-and-local-package-repository[this guide] to set up the directory structure and build a package on the container.
You only need to build the package as shown in the first part of the guide, you don't need to create a repository to host it.
Unfortunately you can't use the `/output` directory to build your package on
a Windows host due to
https://docs.docker.com/docker-for-windows/troubleshoot/#permissions-errors-on-data-directories-for-shared-volumes[permissions
issues].

You can use text editors on the host and save your files in the `output`
directory to copy into the container or you can install an editor to use inside
the container: `apt-get install neovim`, `apt-get install vim`, `apt-get
install nano`, etc.

Make yourself the Maintainer in the metadata, take some credit for your hard
work! When you are all done, copy the `.deb` file to the `/output` directory
and type `exit` to exit the shell.

== Creating a Dockerfile for an Image That Uses Your Package

Take a look at the Dockerfile in the main exercise directory:
`it610/exercises/3`. Makeyour own Dockerfile in the `output` directory that
copies your `.deb` package into the image and installs it with `dpkg -i`.

Relevant documentation can be found here:

* https://docs.docker.com/engine/reference/builder/#from[Dockerfile reference: FROM]
* https://docs.docker.com/engine/reference/builder/#copy[Dockerfile reference: COPY]
* https://docs.docker.com/engine/reference/builder/#run[Dockerfile reference: RUN]
* https://linux.die.net/man/1/dpkg[dpkg man page]

== Questions

Please answer the following questions in the text submission section of the
assignment:

[qanda]
Are there any security concerns with installing an application like GAM via a shell script? Give examples.::
    {empty}
What is the GAM installation script written in? What does it do?::
    {empty}
What are the advantages of having a deb package for GAM as opposed to just using the installation script? What are the disadvantages?::
    {empty}
What was the hardest part of this exercise?::
    {empty}
