= Exercise 5

In this exercise you will be running an ownCloud instance, saving something to
it and creating a backup strategy.

== Getting ownCloud Up and Running

Read the following documentation from ownCloud:

* https://doc.owncloud.com/server/10.10/admin_manual/installation/docker/[Installing with Docker]

Pull the class git repo (you may need to stash your changes from last time) and look in the `exercises/5` directory.
These files are directly from the first doc.
Take a moment to familiarize yourself with them.

Run `docker-compose up` in the `exercises/5` directory and note the information scrolling past.

The `docker-compose.yml` file also has the adminer image running so you can connect to the database and directly manipulate the data stored in its tables.

Visit http://localhost:8080 and sign in using the credentials in the `.env` file. 

== Exploring how ownCloud saves files

Using the ownCloud web interface upload a file.

From another terminal run `docker-compose run owncloud bash` to start a shell.
Use this shell, as well as the contents of `docker-compose.yml` to answer the
questions.

== Questions

[qanda]
Where is the `files` volume mounted in your `owncloud` service?::
    {empty}
Where is the file that you uploaded?::
    {empty}
How could you perform a backup _within_ the running owncloud container?::
    {empty}
How could you perform a backup _outside_ the owncloud container?::
    {empty}
Our volume is currently local, but what type of volume would we typically use with ownCloud in a production environment?::
    {empty}
